### ISSUE TITLE
В репозитории отсутствует файл модели

### ISSUE THREAD

**Issue by QtRoS** [a-milenkin/Toxic_classificator_BERT_pytorch#1]
![image](https://user-images.githubusercontent.com/1700047/109159914-372dbf00-7786-11eb-813f-6e241e07bd2d.png)

```
C:\Temp\Toxic_classificator_BERT_pytorch-main\flaskapp_Milenkin\src>python app.py
Traceback (most recent call last):
  File "app.py", line 136, in <module>
    model_data = torch.load('model/finetuned_BERT_epoch_1.model',  map_location=torch.device('cpu'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model/finetuned_BERT_epoch_1.model'
```

**Comment by a-milenkin** [comment]
Добрый день, Роман!

Да, на самом github модели не было. Не получилось ее залить из-за размера BERT'а и ограничений на github.
Однако, я приложил модель в архиве, который отправлял вам на почту.

Залил модель на Google диск.  Можно скачать по ссылке и залить в папку model:
Ссылка: https://drive.google.com/file/d/1F3qCpasp6qqQIeRX77POUrLaINLXPY4h/view?usp=sharing
